// Part 2: A2 D2, A2 D3
module.exports = function(rows, MC, ES) {
const a2d2_mc = [
  ['past_simple','They ___ a new house last year.',['bought','buyed','buy','buying'],'bought','Irregular past of buy.','buy -> bought.'],
  ['past_simple','I ___ her at the party.',['saw','seen','seed','see'],'saw','Irregular past of see.','see -> saw -> seen.'],
  ['present_continuous','She ___ for her keys now.',['is looking','looks','look','looked'],'is looking','Action in progress.','look for = search.'],
  ['going_to','We ___ travel to Spain in July.',['are going to','will to','going','go to'],'are going to','Future plans.','be going to for plans.'],
  ['comparatives','Math is ___ difficult than art.',['more','most','many','much'],'more','difficult = long adjective.','more + long adjective.'],
  ['superlatives','The Amazon is the ___ river.',['longest','longer','more long','most long'],'longest','Short adj + est.','long -> longest.'],
  ['past_continuous','While I ___, the phone rang.',['was reading','read','reads','reading'],'was reading','Background action.','was/were + -ing for background.'],
  ['past_continuous','What ___ you doing at 5 p.m.?',['were','was','did','are'],'were','you + were.','you/we/they + were.'],
  ['will','Don\u2019t worry. I ___ help you.',['will','am going to','going','would'],'will','Spontaneous decision.','will = offer/decision now.'],
  ['must_should','You ___ park here. It is forbidden.',['must not','should not','don\u2019t must','can not to'],'must not','Prohibition = must not.','must not = prohibition.'],
  ['present_perfect_intro','I ___ just finished my work.',['have','has','had','am'],'have','Present perfect with just.','have/has + just + participle.'],
  ['present_perfect_intro','She ___ lost her phone.',['has','have','had','is'],'has','she + has.','has for 3rd person singular.'],
  ['connectors','I was hungry ___ I made a sandwich.',['so','but','because','or'],'so','Cause-result: so.','so = as a result.'],
  ['connectors','She stayed home ___ she was sick.',['because','so','but','and'],'because','Reason: because.','because introduces reason.'],
  ['adverbs','He runs very ___.',['quickly','quick','quicker','quickness'],'quickly','Adverb modifies verb.','adjective + ly.'],
  ['adverbs','She sings ___.',['well','good','goodly','better'],'well','good -> well (irregular adverb).','well = adverb of good.'],
  ['countable_uncountable','There is not ___ milk left.',['much','many','few','a lot'],'much','Negative + uncountable + much.','much in negatives/questions.'],
  ['countable_uncountable','I need ___ information.',['some','a','an','many'],'some','Uncountable + some.','some + uncountable.'],
  ['past_simple','He did not ___ me yesterday.',['call','called','calling','calls'],'call','After did not use base verb.','did not + base verb.'],
  ['past_simple','Where ___ you go last weekend?',['did','was','were','do'],'did','Past question with did.','did + subject + base.'],
  ['present_continuous','They ___ not working today.',['are','is','do','does'],'are','they + are.','are + not + -ing.'],
  ['going_to','She ___ study medicine.',['is going to','will going','goes to','going to'],'is going to','3rd person singular + going to.','is/am/are + going to + base.'],
  ['comparatives','Today is ___ than yesterday.',['hotter','hoter','more hot','hottest'],'hotter','Double consonant + er.','CVC pattern: double + er.'],
  ['superlatives','Who is the ___ person you know?',['funniest','most funny','funnyest','funier'],'funniest','y -> i + est.','y ending: y->i+est.'],
  ['past_continuous','They ___ football when it started to rain.',['were playing','played','are playing','play'],'were playing','Interrupted ongoing action.','past continuous + past simple.'],
  ['will','I ___ be 30 next year.',['will','am going','go','do'],'will','Future fact.','will for facts/predictions.'],
  ['must_should','You look tired. You ___ rest.',['should','must','can','could'],'should','Advice.','should + base for advice.'],
  ['present_perfect_intro','___ you ever eaten sushi?',['Have','Has','Did','Do'],'Have','you + have.','Have/Has + subject + participle.'],
  ['connectors','I was tired ___ I continued working.',['but','so','because','and'],'but','Contrast.','but = however.'],
  ['countable_uncountable','How ___ sugar do you want?',['much','many','few','lots'],'much','sugar = uncountable.','much + uncountable.'],
  ['adverbs','She always arrives ___.',['late','lately','later','latest'],'late','late is adverb and adjective.','late = both; lately = recently.'],
  ['going_to','They are not ___ come.',['going to','will','going','go to'],'going to','Negative form of going to.','are not going to + base.'],
];
const a2d2_es = [
  ['past_simple','Describe a memorable trip in 4 sentences.','Last summer I went to the beach. I stayed in a hotel. I swam every day. I ate fresh seafood.','Use past simple.','irregular verbs: went, ate, swam.'],
  ['going_to','Describe 4 plans for next month.','I am going to start a new course. I am going to visit my uncle. I am going to save money. I am going to read more books.','Use going to for plans.','concrete plans = going to.'],
  ['comparatives','Compare two hobbies (4 sentences).','Reading is more relaxing than gaming. Gaming is more exciting than reading. Gaming is more expensive. Reading is easier to do anywhere.','Use more/than for long adj.','long adj: more + adj + than.'],
  ['past_continuous','Describe what was happening at a party (4 sentences).','People were dancing. Some were eating. Kids were playing. The music was playing loudly.','Use past continuous.','was/were + ing.'],
  ['present_perfect_intro','Write 4 things you have done in your life.','I have visited Spain. I have eaten Japanese food. I have climbed a mountain. I have learned two languages.','Use have/has + participle.','life experiences = present perfect.'],
  ['will','Write 4 predictions for next year.','I will finish my studies. I will travel abroad. I will get a new job. I will buy a car.','Use will for predictions.','will + base verb.'],
  ['must_should','Give 4 pieces of advice to a new student.','You should arrive early. You must bring your book. You should take notes. You must not use your phone in class.','Mix should/must.','should advice, must obligation.'],
  ['connectors','Write a short story with connectors (4 sentences).','I was tired but I had to work. I made coffee because I needed energy. I worked hard so I finished early. Then I went home and slept.','Use but/so/because/and.','Link ideas clearly.'],
];
a2d2_mc.forEach(a=>rows.push(MC('A2',2,...a)));
a2d2_es.forEach(a=>rows.push(ES('A2',2,...a)));

const a2d3_mc = [
  ['past_simple','When I was a child, I ___ to play outside.',['used','use','using','use to'],'used','used to + base.','used to = past habit.'],
  ['past_simple','She ___ the truth yesterday.',['told','tell','telled','tolded'],'told','Irregular past.','tell -> told.'],
  ['present_perfect_intro','They ___ lived here since 2010.',['have','has','had','are'],'have','Plural subject + have.','for/since + present perfect.'],
  ['present_perfect_intro','He ___ finished his project.',['has not','have not','did not','is not'],'has not','3rd person singular negative.','has not = hasn\u2019t.'],
  ['going_to','I am not ___ wait anymore.',['going to','will to','go to','going'],'going to','Negative going to.','not going to + base.'],
  ['past_continuous','While she ___, he arrived.',['was cooking','cooked','cooks','is cooking'],'was cooking','Background action in past.','while + past continuous.'],
  ['comparatives','This test is ___ than the last one.',['less difficult','lesser difficult','more less','most less'],'less difficult','less + adj for comparison down.','less = opposite of more.'],
  ['superlatives','He is the ___ worker in the team.',['hardest','most hard','harder','hardly'],'hardest','Short adj + est.','hard -> hardest.'],
  ['will','I promise I ___ call you later.',['will','am going to','going','would'],'will','Promise = will.','will = promise/offer.'],
  ['must_should','You ___ be over 18 to drive.',['must','should','can','may'],'must','Rule = must.','must for rules.'],
  ['connectors','She was late ___ of the traffic.',['because','so','but','for'],'because','because of + noun.','because + clause, because of + noun.'],
  ['connectors','___ it was raining, we went out.',['Although','Because','So','But'],'Although','Contrast at start.','although = even though.'],
  ['adverbs','He finished ___ easily.',['quite','quiet','quieter','quietly'],'quite','quite = intensifier.','quite + adverb.'],
  ['adverbs','She almost ___ forgot my name.',['completely','complete','completion','completeness'],'completely','Two adverbs.','almost + adverb.'],
  ['countable_uncountable','I do not have ___ time.',['enough','many','few','lot'],'enough','enough + uncountable.','enough + noun.'],
  ['countable_uncountable','There are ___ of apples.',['lots','a lot','much','many'],'lots','lots of + any noun.','lots of = a lot of.'],
  ['past_simple','They ___ married in 2020.',['got','get','gets','getted'],'got','Irregular past of get.','get -> got.'],
  ['past_simple','She did not ___ the email.',['receive','received','receives','receiving'],'receive','After did not use base.','did not + base.'],
  ['present_continuous','I ___ studying these days.',['am','do','have','is'],'am','I + am.','I am + ing.'],
  ['going_to','What ___ they going to do?',['are','is','do','have'],'are','Plural + are going to.','they are going to.'],
  ['comparatives','He is ___ older than his sister.',['much','more','very','well'],'much','much + comparative for emphasis.','much/far + comparative.'],
  ['superlatives','Mount Everest is one of the ___ mountains.',['highest','most high','higher','highly'],'highest','Short adj: est.','high -> highest.'],
  ['past_continuous','I was reading ___ you called.',['when','while','during','since'],'when','when + past simple event.','while + ongoing, when + event.'],
  ['will','I think Brazil ___ win the cup.',['will','is going to','would','might'],'will','Prediction with think.','I think + will.'],
  ['must_should','You ___ eat too much sugar.',['should not','must not','cannot','will not'],'should not','Advice against.','should not = negative advice.'],
  ['present_perfect_intro','I ___ known her for 10 years.',['have','has','had','having'],'have','I + have.','for + period.'],
  ['present_perfect_intro','She ___ lived there since June.',['has','have','had','is'],'has','she + has.','since + point in time.'],
  ['connectors','I like both coffee ___ tea.',['and','or','but','so'],'and','both...and.','both X and Y.'],
  ['connectors','We can eat pizza ___ pasta.',['or','but','so','because'],'or','Choice: or.','or = alternative.'],
  ['adverbs','She works very ___.',['hard','hardly','harder','hardest'],'hard','hard = adverb too.','hardly = almost not!'],
  ['countable_uncountable','There is ___ bread left.',['a little','a few','many','several'],'a little','a little + uncountable.','a little = small amount uncountable.'],
  ['countable_uncountable','I have ___ friends here.',['a few','a little','much','less'],'a few','a few + countable plural.','a few = small number countable.'],
];
const a2d3_es = [
  ['past_experience','Describe a memorable day in 4 sentences using past tenses.','I was walking in the park when it started to rain. I ran to a cafe. I ordered a hot chocolate. I met an old friend there.','Mix past simple and continuous.','while/when + correct tense.'],
  ['future_plans','Write 4 sentences about your career plans.','I am going to finish my degree next year. I will look for a job. I hope I will work abroad. I am going to save money.','Mix going to and will.','going to = plans, will = predictions.'],
  ['comparisons','Compare life in the city and countryside (4 sentences).','The city is more exciting than the countryside. The countryside is quieter. Cities are more expensive. Life in the countryside is healthier.','Use comparatives and superlatives.','more/less, -er/-est.'],
  ['present_perfect_intro','Write 4 life experiences using ever/never.','I have never been to Japan. I have eaten sushi. I have met a famous person once. I have never tried skydiving.','Use have/has + participle.','ever/never with present perfect.'],
  ['advice','Give advice to a friend moving abroad (4 sentences).','You should learn the language. You must get insurance. You should not forget your documents. You should make local friends.','Use should/must.','should advice, must essentials.'],
  ['connectors','Write a paragraph about a difficult decision (4 sentences).','I wanted to change jobs but I was afraid. Although the new job paid more, it was far away. I finally accepted because I needed a change. Now I am happy with my choice.','Use multiple connectors.','but/although/because.'],
  ['past_continuous','Describe a scene from last week (4 sentences).','It was 7 pm and the sun was setting. People were walking home. Children were playing. I was enjoying the view.','Use past continuous for scene.','Set the scene with was/were + ing.'],
  ['predictions','Make 4 predictions about technology.','Robots will do more jobs. Cars will drive themselves. People will use less cash. We will all have smart homes.','Use will for predictions.','will + base verb.'],
];
a2d3_mc.forEach(a=>rows.push(MC('A2',3,...a)));
a2d3_es.forEach(a=>rows.push(ES('A2',3,...a)));
};
