// Part 6: C2 D1, D2, D3
module.exports = function(rows, MC, ES) {
// C2 D1
const c2d1_mc = [
  ['literary','The author''s prose is remarkably ___.',['evocative','evoke','evocation','evoked'],'evocative','evocative = rich in imagery.','evocative = suggestive.'],
  ['literary','Her writing displays a rare ___ of voice.',['felicity','facility','faculty','fidelity'],'felicity','felicity = aptness/grace.','felicity = appropriateness.'],
  ['philosophical','The argument rests on a questionable ___.',['premise','premisses','premium','premiere'],'premise','premise = assumption.','premise = basis.'],
  ['philosophical','Such claims are ___ unverifiable.',['inherently','inherent','inheriting','inherence'],'inherently','adverb needed.','inherently = by nature.'],
  ['connotation','His tone was notably ___, bordering on scornful.',['caustic','cautious','courteous','cautionary'],'caustic','caustic = sharply critical.','caustic = biting.'],
  ['connotation','She offered a ___ smile.',['rueful','rustic','rural','rude'],'rueful','rueful = regretful.','rueful = showing regret.'],
  ['rhetoric','The speaker used ___ to great effect.',['anaphora','anorexia','amphora','analogy'],'anaphora','anaphora = repetition.','anaphora = rhetorical repetition.'],
  ['rhetoric','His speech was marked by skilful ___.',['antithesis','antibiotic','anthesis','anthology'],'antithesis','antithesis = contrast.','antithesis = contrasted ideas.'],
  ['ambiguity','The phrase is deliberately ___.',['oblique','obligate','oblivious','obstinate'],'oblique','oblique = indirect.','oblique = not straightforward.'],
  ['ambiguity','Her remarks were frustratingly ___.',['elliptical','eliptical','elected','elevated'],'elliptical','elliptical = cryptic.','elliptical = leaving out words.'],
  ['collocations','The proposal was met with a ___ reception.',['lukewarm','lukewarmly','luke','warmly'],'lukewarm','lukewarm reception = unenthusiastic.','lukewarm = tepid.'],
  ['collocations','He harboured ___ doubts.',['lingering','long','late','lately'],'lingering','lingering doubts.','lingering = persistent.'],
  ['register_precision','The findings were ___ inconclusive.',['decidedly','decided','decide','decision'],'decidedly','adverb.','decidedly = clearly/definitely.'],
  ['register_precision','His views are ___ nuanced.',['exceedingly','exceed','excess','exceeded'],'exceedingly','adverb = extremely.','exceedingly = extremely (formal).'],
  ['complex_syntax','Such was the ___ of the response that...',['vehemence','vehement','vehemently','vehemences'],'vehemence','noun after such was the.','vehemence = intensity.'],
  ['complex_syntax','Were it ___ for his intervention...',['not','no','never','nothing'],'not','were it not for = without.','formal counterfactual.'],
  ['stylistic','The sentence demonstrates skilful use of ___.',['parallelism','parallels','parallel','parallelly'],'parallelism','noun.','parallelism = balanced structure.'],
  ['stylistic','The writer''s ___ is deliberately restrained.',['diction','dictate','dictation','diction'],'diction','diction = word choice.','diction = vocabulary choice.'],
  ['literary','The poem evokes a ___ sense of loss.',['poignant','pointless','poignantly','point'],'poignant','adjective.','poignant = deeply moving.'],
  ['philosophical','The concept is notoriously difficult to ___.',['pin down','pin up','pin on','pin off'],'pin down','pin down = define precisely.','pin down = identify.'],
  ['connotation','She spoke with ___ authority.',['quiet','quietly','quietness','quieted'],'quiet','adjective before noun.','quiet = understated.'],
  ['rhetoric','His ___ was impeccable throughout.',['delivery','deliver','delivered','delivering'],'delivery','noun.','delivery = manner of speaking.'],
  ['ambiguity','The author leaves the ending deliberately ___.',['open','opened','opening','opens'],'open','adjective.','open ending = ambiguous.'],
  ['collocations','She drew ___ parallels between the two periods.',['striking','strike','struck','strikingly'],'striking','striking parallels.','striking = remarkable.'],
  ['register_precision','His response was ___ evasive.',['conspicuously','conspicuous','conspicuousness','conspicuity'],'conspicuously','adverb.','conspicuously = noticeably.'],
  ['complex_syntax','Had it not been ___, we would have succeeded.',['for him','him','his','he'],'for him','had it not been for + noun.','formal past counterfactual.'],
  ['stylistic','The novel''s ___ structure mirrors its themes.',['fragmented','fragments','fragmenting','fragment'],'fragmented','adjective.','fragmented = broken up.'],
  ['literary','The prose is laced with ___ irony.',['subtle','subtly','subtlety','subtileness'],'subtle','adjective.','subtle irony.'],
  ['philosophical','The theory ___ several assumptions.',['presupposes','proposes','possesses','predicts'],'presupposes','presuppose = assume beforehand.','presuppose = take for granted.'],
  ['connotation','The comment carried a faintly ___ tone.',['patronising','patron','patronage','patronised'],'patronising','adjective.','patronising = condescending.'],
  ['rhetoric','The metaphor is ___.',['apt','ape','apex','apex'],'apt','apt = fitting.','apt = appropriate.'],
  ['ambiguity','The meaning remains ___.',['elusive','elude','eluded','eluding'],'elusive','adjective.','elusive = hard to grasp.'],
];
const c2d1_es = [
  ['literary_analysis','Write a 4-sentence literary analysis of a novel.','The novel''s fractured chronology mirrors the protagonist''s disintegrating psyche. Time itself becomes a character, elusive and unreliable. The author''s spare prose belies the emotional weight of each scene. Ultimately, the work interrogates the very nature of memory.','Use literary vocabulary.','fractured, disintegrating, elusive, interrogate.'],
  ['philosophical','Discuss a philosophical concept in 4 sentences.','Free will, as traditionally conceived, presupposes an agent capable of alternative actions. Yet determinism challenges this presupposition at its root. The compatibilist response seeks to reconcile the two, though not without residual difficulties. The debate, far from settled, continues to generate sophisticated argumentation.','Use philosophical register.','presuppose, reconcile, residual, generate.'],
  ['rhetorical','Write a 4-sentence rhetorically rich passage.','We stand not at the end of an era, but at its rebirth. We have been tested, we have been divided, yet we have endured. Let us remember, then, not what divides but what unites. For in unity lies not merely strength, but purpose.','Use rhetorical devices.','anaphora, antithesis, inversion.'],
  ['nuanced_opinion','Write a nuanced 4-sentence opinion.','While recent reforms have been widely celebrated, their long-term implications remain uncertain. The measures address symptoms rather than causes, a distinction often overlooked. To dismiss them as inadequate, however, would be both unfair and unhelpful. What is needed, rather, is a reasoned assessment informed by evidence.','Express nuanced positions.','remain uncertain, distinction, unhelpful.'],
  ['stylistic','Write 4 sentences demonstrating stylistic variety.','She paused. Then, with a composure she did not feel, she began to speak. Words came haltingly at first, then in a torrent, then not at all. The silence that followed was, in its way, the most eloquent speech of all.','Vary sentence length and rhythm.','stylistic variation for effect.'],
  ['connotation','Use 4 words with precise connotations.','He delivered a blistering critique of the proposal. Her manner was disarmingly candid. The room fell into a pregnant silence. His concession was both reluctant and magnanimous.','Use words with strong connotation.','blistering, disarming, pregnant, magnanimous.'],
  ['ambiguity','Craft 4 deliberately ambiguous sentences.','She decided, in the end, to go. He said nothing, and that said everything. The truth, if that is what it was, came later. They left together, though not, perhaps, in the same direction.','Use ambiguity artistically.','deliberate open interpretation.'],
  ['register','Write 4 sentences in elevated literary register.','The afternoon light fell obliquely across the marble floor, rendering familiar objects strange. From the garden came the desultory song of a solitary bird. She sat motionless, as if any motion might shatter the fragile calm. Time, it seemed, had quietly withdrawn from the room.','Use literary register.','obliquely, desultory, motionless, fragile.'],
];
c2d1_mc.forEach(a=>rows.push(MC('C2',1,...a)));
c2d1_es.forEach(a=>rows.push(ES('C2',1,...a)));

// C2 D2
const c2d2_mc = [
  ['literary','The text is ___ with biblical allusion.',['replete','repleat','repletion','repletely'],'replete','replete with = full of.','replete = abundantly supplied.'],
  ['literary','Her style is ___ spare yet resonant.',['at once','one','at time','by once'],'at once','at once + adj + and adj.','at once X and Y.'],
  ['philosophical','The distinction is ___ rather than substantive.',['semantic','semantics','semantically','seminar'],'semantic','adjective.','semantic = about meaning.'],
  ['philosophical','His reasoning ___ the question.',['begs','bugs','begs','starts'],'begs','beg the question = assume.','beg the question (correct usage).'],
  ['connotation','The speech was received with ___ enthusiasm.',['muted','mute','muting','mutedly'],'muted','muted = subdued.','muted enthusiasm.'],
  ['connotation','Her gaze was ___.',['withering','wither','withered','witheringly'],'withering','adjective = scornful.','withering glance.'],
  ['rhetoric','The essay builds to a ___ crescendo.',['rhetorical','rhetoric','rhetorically','rhetorician'],'rhetorical','adjective.','rhetorical crescendo.'],
  ['rhetoric','He deployed ___ to devastating effect.',['irony','irons','ironically','ironic'],'irony','noun.','deploy irony.'],
  ['ambiguity','The statement admits of multiple ___.',['readings','readers','reads','reading''s'],'readings','readings = interpretations.','reading = interpretation.'],
  ['ambiguity','The ending is pointedly ___.',['inconclusive','inconclusion','inconclusively','inconclude'],'inconclusive','adjective.','inconclusive = not definitive.'],
  ['collocations','The author''s claim ___ considerable weight.',['carries','makes','takes','does'],'carries','carry weight.','carry weight = influence.'],
  ['collocations','The book ___ light on a neglected topic.',['sheds','puts','throws','makes'],'sheds','shed light on.','shed light = illuminate.'],
  ['register_precision','His argument is ___ persuasive.',['decidedly','decided','deciding','decision'],'decidedly','adverb.','decidedly = definitely.'],
  ['register_precision','The assessment proved ___ accurate.',['uncannily','uncanny','uncannyness','uncannier'],'uncannily','adverb.','uncannily = strangely.'],
  ['complex_syntax','Not ___ is he brilliant, he is also kind.',['only','just','even','merely'],'only','not only...(but) also.','not only + inversion.'],
  ['complex_syntax','Rarely ___ I encountered such insight.',['have','had','do','am'],'have','present perfect inversion.','rarely + have + subject + part.'],
  ['stylistic','The paragraph employs skilful ___.',['chiasmus','chasm','chasten','chase'],'chiasmus','chiasmus = reversed structure.','chiasmus = ABBA pattern.'],
  ['stylistic','Her prose is marked by striking ___.',['cadence','cadenced','cadences','cadently'],'cadence','noun.','cadence = rhythm.'],
  ['literary','The imagery is strikingly ___.',['visceral','viscous','vicinity','viscerally'],'visceral','adjective.','visceral = gut-level.'],
  ['philosophical','The thesis is ___ to refutation.',['impervious','impervously','impervious','impervy'],'impervious','adjective.','impervious to = resistant.'],
  ['connotation','His tone was ___ avuncular.',['faintly','faint','faintness','fainted'],'faintly','adverb.','faintly avuncular = slightly uncle-like.'],
  ['rhetoric','The speech deployed ___ with mastery.',['metonymy','metabolism','metaphor''s','metonyms'],'metonymy','noun.','metonymy = substitution.'],
  ['ambiguity','The truth, ___, was complex.',['as ever','as always','as all','as such'],'as ever','idiomatic.','as ever = as usual.'],
  ['collocations','The findings ___ a spotlight on inequality.',['shine','show','put','make'],'shine','shine a spotlight.','shine a spotlight = highlight.'],
  ['register_precision','The outcome was ___ predictable.',['eminently','eminent','eminence','eminency'],'eminently','adverb.','eminently = clearly/highly.'],
  ['complex_syntax','So ___ is the theory that few challenge it.',['entrenched','entrench','entrenchment','entrenchly'],'entrenched','past participle adj.','entrenched = firmly established.'],
  ['stylistic','The narrative shifts through multiple ___.',['registers','register','registered','registering'],'registers','registers = styles.','register = linguistic variety.'],
  ['literary','The novel is a ___ of the era.',['tapestry','tapestries','tapestry''s','tapestried'],'tapestry','metaphorical noun.','tapestry = rich portrayal.'],
  ['philosophical','The theory is ___ circular.',['arguably','argue','argued','argument'],'arguably','adverb.','arguably = it can be argued.'],
  ['connotation','The portrait is ___ affectionate.',['guardedly','guardedness','guarded','guard'],'guardedly','adverb.','guardedly = cautiously.'],
  ['rhetoric','The essay opens with an arresting ___.',['paradox','paradise','paradigm','parade'],'paradox','noun.','paradox = contradiction.'],
  ['ambiguity','The implication is ___ troubling.',['faintly','faint','fainting','fainted'],'faintly','adverb.','faintly = slightly.'],
];
const c2d2_es = [
  ['analytical','Analyze a cultural phenomenon in 4 sentences.','The phenomenon defies straightforward classification, resisting the categories typically invoked. It emerges at the confluence of economic, technological, and cultural currents, each exerting its own pressure. To treat any single dimension as primary would be to impoverish the analysis. What is required, rather, is an account capable of honouring the phenomenon''s constitutive complexity.','Use advanced analytical language.','confluence, exert, impoverish, constitutive.'],
  ['rhetorical','Compose a rhetorically crafted 4-sentence passage.','We inherit a world we did not make, and which we are charged to remake. We did not choose the burdens of history, yet we must bear them. But we can, if we will it, choose the future. And in that choosing lies our freedom, our responsibility, our hope.','Use rhetorical devices.','anaphora, chiasmus, tricolon.'],
  ['philosophical','Argue a philosophical position (4 sentences).','To suppose that meaning inheres in the text alone is to neglect the reader''s constitutive role. Interpretation is not a passive recovery but an active co-production. This is not to surrender to relativism; interpretations remain answerable to evidence. Rather, it is to acknowledge that meaning is relational and historically situated.','Use philosophical rigor.','inhere, constitutive, surrender, relational.'],
  ['literary_review','Review a novel (4 sentences).','This is a novel of quiet devastation, its power lying less in what happens than in what is withheld. The prose moves with a lapidary precision, each sentence weighted and unhurried. The characters, for all their specificity, seem to stand for something larger than themselves. It is, in the end, a book about the slow accumulation of loss.','Use literary critical register.','lapidary, withheld, accumulation.'],
  ['nuanced','Write 4 sentences with nuanced qualification.','The argument, though compelling in its broad strokes, falters in the detail. There is much here to admire; there is equally much to contest. To call the project a failure would be both inaccurate and ungenerous; to call it a success would be premature. Perhaps, in the end, these binaries do less work than we imagine.','Qualify claims precisely.','broad strokes, falter, contest, premature.'],
  ['aphoristic','Write 4 aphoristic sentences.','Power, unexamined, corrupts quietly. Truth is seldom as pure as those who claim it. We distrust most those whose virtues mirror our failures. The future, like the past, will be misremembered.','Craft memorable concise statements.','aphoristic compression.'],
  ['essay_intro','Write an essay introduction (4 sentences).','Few concepts are at once so familiar and so elusive as that of identity. Invoked daily in contexts from the political to the intimate, it resists the very coherence it purports to confer. This essay sets out to map the fault lines of that paradox. It argues that identity is best understood not as an essence but as a practice.','Use essayistic style.','familiar, elusive, fault lines, practice.'],
  ['ironic','Write 4 sentences employing irony.','It is, of course, a remarkable coincidence that the committee''s findings so exactly accord with the preferences of those who appointed it. We are assured that this is mere accident. One is reassured, naturally, by the gravity with which this assurance is offered. Whether the public will share this reassurance is another matter entirely.','Use sustained irony.','sustained ironic register.'],
];
c2d2_mc.forEach(a=>rows.push(MC('C2',2,...a)));
c2d2_es.forEach(a=>rows.push(ES('C2',2,...a)));

// C2 D3
const c2d3_mc = [
  ['literary','The work stands as a ___ of postwar sensibility.',['lodestone','lodestar','lodging','loading'],'lodestar','lodestar = guiding light.','lodestar metaphor.'],
  ['literary','Her sentences have an almost ___ quality.',['incantatory','incantation','incanted','incant'],'incantatory','adjective.','incantatory = like a chant.'],
  ['philosophical','The position is epistemologically ___.',['untenable','untenant','untenability','untenably'],'untenable','adjective.','untenable = indefensible.'],
  ['philosophical','The concept ___ further scrutiny.',['invites','asks','tells','says'],'invites','invite scrutiny.','invite = call for.'],
  ['connotation','The remark was ___ condescending.',['patently','patent','patency','patience'],'patently','adverb.','patently = obviously.'],
  ['connotation','His manner was ___ deferential.',['studiously','studied','studying','studies'],'studiously','adverb.','studiously = deliberately.'],
  ['rhetoric','The passage employs ___ to great effect.',['zeugma','zebra','zest','zero'],'zeugma','zeugma = one word applying to two.','rhetorical figure.'],
  ['rhetoric','His speech achieved genuine ___.',['eloquence','eloquent','eloquently','eloquences'],'eloquence','noun.','eloquence = expressive power.'],
  ['ambiguity','The conclusion is ___ open.',['artfully','art','arts','artfulness'],'artfully','adverb.','artfully = skillfully.'],
  ['ambiguity','The text resists ___ readings.',['reductive','reduce','reduced','reduction'],'reductive','adjective.','reductive = oversimplifying.'],
  ['collocations','The analysis ___ to the heart of the matter.',['cuts','makes','takes','goes'],'cuts','cut to the heart.','cut to = reach directly.'],
  ['collocations','The argument ___ itself.',['belies','betrays','believes','belittles'],'belies','belie = contradict.','belie itself = undermine.'],
  ['register_precision','The account is ___ plausible.',['eminently','eminent','eminence','eminency'],'eminently','adverb.','eminently = clearly.'],
  ['register_precision','The evidence is ___ ambiguous.',['tantalisingly','tantalise','tantalised','tantalising'],'tantalisingly','adverb.','tantalisingly = teasingly.'],
  ['complex_syntax','Such ___ his erudition that few could follow.',['was','were','is','did'],'was','such + was + noun.','such + be + noun + that.'],
  ['complex_syntax','Not ___ in decades has the country seen such unrest.',['since','for','during','throughout'],'since','not since + time.','not since X has/have.'],
  ['stylistic','The novel''s prose shimmers with unexpected ___.',['felicities','felicity','felicitous','felicitously'],'felicities','plural noun.','felicity = apt expression.'],
  ['stylistic','The writer''s ___ of tone is masterful.',['modulation','modulate','modulated','modulating'],'modulation','noun.','modulation = variation.'],
  ['literary','The poem is a ___ of grief and memory.',['meditation','meditate','meditated','meditating'],'meditation','noun.','meditation on = reflection.'],
  ['philosophical','The theory remains ___ contested.',['hotly','hot','heat','hotter'],'hotly','adverb.','hotly contested.'],
  ['connotation','The gesture was ___ if ambiguous.',['conciliatory','conciliation','conciliated','conciliate'],'conciliatory','adjective.','conciliatory = peace-making.'],
  ['rhetoric','The essay ___ with a challenge.',['culminates','culminate','culminated','culmination'],'culminates','3rd person verb.','culminate in = end with.'],
  ['ambiguity','The meaning remains ___ elusive.',['maddeningly','maddened','madden','madness'],'maddeningly','adverb.','maddeningly = frustratingly.'],
  ['collocations','Her insights ___ the status quo.',['unsettle','unset','unsetting','unsettled'],'unsettle','verb.','unsettle = disturb.'],
  ['register_precision','The distinction is ___ fine.',['vanishingly','vanish','vanished','vanishing'],'vanishingly','adverb.','vanishingly = extremely.'],
  ['complex_syntax','So ___ was her reasoning that no reply was possible.',['unassailable','unassail','unassailably','unassailability'],'unassailable','adjective.','so + adj + be + subject.'],
  ['stylistic','The book ___ a world of quiet intensity.',['conjures','conjure','conjured','conjuring'],'conjures','3rd person verb.','conjure = evoke.'],
  ['literary','The novel is a ___ achievement.',['singular','single','singularly','singularity'],'singular','adjective.','singular = extraordinary.'],
  ['philosophical','The framework ___ a fundamental tension.',['occludes','ocludes','occluded','occluding'],'occludes','verb.','occlude = obscure.'],
  ['connotation','The praise was ___ fulsome.',['embarrassingly','embarrassed','embarrassment','embarrass'],'embarrassingly','adverb.','embarrassingly fulsome.'],
  ['rhetoric','The speech achieved a rare ___ of clarity.',['lucidity','lucid','lucidly','lucidities'],'lucidity','noun.','lucidity = clarity.'],
  ['ambiguity','The portrait is ___ inscrutable.',['hauntingly','haunting','haunted','haunt'],'hauntingly','adverb.','hauntingly = memorably.'],
];
const c2d3_es = [
  ['literary_criticism','Write 4 sentences of sophisticated literary criticism.','The novel''s achievement lies precisely in what it refuses: the consolations of resolution, the comfort of sympathetic characters, the reassurance of a stable narrative voice. What remains is more austere and more demanding: a prose that trusts the reader to dwell in difficulty. It is not a book that rewards impatience. Its pleasures, like its meanings, emerge only under the pressure of sustained attention.','Use sophisticated literary register.','consolation, austere, dwell, sustained.'],
  ['philosophical_argument','Argue a subtle philosophical claim (4 sentences).','The very coherence of personal identity across time is, on closer inspection, harder to sustain than we suppose. What binds the child we were to the adult we have become is not any enduring substance but a continuity of narrative, itself always under revision. To the extent that we are anything stable, we are a story we tell ourselves, and retell. This is not a reduction but an illumination: we are authors as well as characters of the selves we live.','Use philosophical precision.','coherence, sustain, enduring, illumination.'],
  ['aphoristic_essay','Write 4 aphoristic sentences for an essay.','The present is always the past''s unfinished sentence. We mistake familiarity for understanding; the two are seldom allies. What we call memory is less recovery than reconstruction, and reconstruction under pressure. The future has this advantage over the past: it permits us our illusions.','Craft aphoristic density.','compressed thought.'],
  ['rhetorical_speech','Compose 4 sentences of a rhetorical address.','We gather today not to commemorate what has ended but to consecrate what is still beginning. We came here bearing grief; we must leave bearing resolve. We cannot undo what is done, but we can refuse to let it be the last word. Let our answer to this loss be a life worthier of what was lost.','Use rhetorical devices.','anaphora, antithesis.'],
  ['high_register','Write 4 sentences in elevated formal register.','It is with considerable regret, and no little deliberation, that I find myself obliged to decline the invitation. The reasons are less a matter of principle than of practical necessity, though the distinction may be small consolation. Were circumstances different, my response would be, and would have been, otherwise. I trust that my absence will be received in the spirit it is offered.','Use elevated diction.','obliged, deliberation, consolation.'],
  ['nuanced_critique','Write a 4-sentence nuanced critique.','The book''s ambition is both its strength and, paradoxically, its limit. What it attempts deserves admiration; what it achieves deserves scrutiny. Certain chapters move with real grace; others labour under the weight of their own claims. The final effect, for all that, is of a mind working seriously on questions that merit seriousness.','Balance critique with recognition.','ambition, labour, merit.'],
  ['oblique','Write 4 oblique, suggestive sentences.','She did not answer, and in not answering answered everything. The room held, for a moment, the silence that follows what cannot be said. Later, she would describe the afternoon as uneventful, and perhaps, for her, it was. Some things, she had come to believe, were better left where they lay.','Use suggestive ambiguity.','indirection, suggestion.'],
  ['stylistic_virtuosity','Write 4 sentences demonstrating stylistic virtuosity.','Dusk came, as dusk comes in that country, not gradually but all at once, and with it a silence older than the town itself. The olive trees, black now against the sky, stood as they had stood for centuries, patient and indifferent. From somewhere, a bell; from somewhere else, an answering bell, and then nothing. She remembered, then, why she had come, and why, perhaps, she would not leave.','Use stylistic range.','rhythm, repetition, evocation.'],
];
c2d3_mc.forEach(a=>rows.push(MC('C2',3,...a)));
c2d3_es.forEach(a=>rows.push(ES('C2',3,...a)));
};
