// Part 3: B1 D1, D2, D3
module.exports = function(rows, MC, ES) {
// B1 D1
const b1d1_mc = [
  ['present_perfect','I have lived here ___ 2015.',['since','for','from','ago'],'since','since + point in time.','since + starting point.'],
  ['present_perfect','She has worked here ___ ten years.',['for','since','during','ago'],'for','for + duration.','for + period of time.'],
  ['present_perfect','They ___ finished the project yet.',['have not','did not','do not','had not'],'have not','yet + present perfect negative.','yet at end of negatives/questions.'],
  ['present_perfect','___ you ever visited London?',['Have','Has','Did','Do'],'Have','Experience question.','Have/Has + ever + participle.'],
  ['first_conditional','If it rains, we ___ stay home.',['will','would','would have','will have'],'will','1st conditional: if + present, will + base.','real future: if + present, will.'],
  ['first_conditional','If you ___ early, you will catch the bus.',['leave','left','leaves','will leave'],'leave','if + present simple.','if-clause uses present simple.'],
  ['second_conditional','If I ___ rich, I would travel.',['were','was','am','be'],'were','2nd conditional uses were for all.','If I were... (hypothetical).'],
  ['second_conditional','She would help if she ___ time.',['had','has','have','will have'],'had','2nd conditional: past simple.','if + past simple, would + base.'],
  ['passive_voice','The book ___ by many people.',['is read','reads','read','reading'],'is read','Present passive.','be + past participle.'],
  ['passive_voice','The letter was ___ yesterday.',['sent','send','sending','sends'],'sent','Past passive.','was/were + participle.'],
  ['reported_speech','He said he ___ tired.',['was','is','be','were'],'was','Present -> past in reported.','tense backshift.'],
  ['reported_speech','She told me she ___ come.',['would','will','can','may'],'would','will -> would.','will becomes would.'],
  ['phrasal_verbs','Please ___ off your shoes.',['take','make','do','put'],'take','take off = remove.','take off clothes/shoes.'],
  ['phrasal_verbs','I need to ___ up early.',['get','take','give','stand'],'get','get up = leave bed.','get up in the morning.'],
  ['relative_clauses','The man ___ lives next door is nice.',['who','which','whose','where'],'who','who for people.','who = for people.'],
  ['relative_clauses','The book ___ I bought is great.',['which','who','whose','where'],'which','which for things.','which/that for things.'],
  ['modal_verbs','You ___ be tired after the trip.',['must','can','should','would'],'must','deduction = must.','must = strong certainty.'],
  ['modal_verbs','It ___ rain later; bring an umbrella.',['might','must','can','will'],'might','possibility = might.','might = possibility.'],
  ['linking_words','___, I passed the exam.',['Finally','Final','Ending','Last'],'Finally','Sentence adverb.','Finally = at last.'],
  ['linking_words','I was tired. ___, I finished.',['However','Because','So','Then'],'However','Contrast.','However starts a new idea with comma.'],
  ['present_perfect','He has ___ lived abroad.',['never','ever','since','for'],'never','never + participle.','never = not once.'],
  ['first_conditional','If you study, you ___ pass.',['will','would','shall','have'],'will','Real future.','will + base.'],
  ['second_conditional','I ___ travel if I had time.',['would','will','can','do'],'would','Hypothetical.','would + base verb.'],
  ['passive_voice','English ___ all over the world.',['is spoken','speaks','spoken','speaking'],'is spoken','Present simple passive.','is/are + participle.'],
  ['reported_speech','He said, "I am happy." -> He said he ___ happy.',['was','is','were','be'],'was','Backshift.','am/is -> was, are -> were.'],
  ['phrasal_verbs','Can you ___ me up at 7?',['pick','take','give','get'],'pick','pick up = collect.','pick up = collect someone.'],
  ['relative_clauses','That is the house ___ I was born.',['where','which','who','when'],'where','where for places.','where = in which place.'],
  ['modal_verbs','You ___ smoke here, it is prohibited.',['must not','do not have to','should not','might not'],'must not','Prohibition.','must not = prohibition.'],
  ['linking_words','I like tea. ___, I do not drink coffee.',['However','Because','So','Although'],'However','Contrast between sentences.','However separates ideas.'],
  ['present_perfect','We ___ just arrived.',['have','has','are','did'],'have','we + have + just + participle.','just = recently.'],
  ['first_conditional','Unless you hurry, you ___ be late.',['will','would','are','have'],'will','unless = if not.','unless + present + will.'],
  ['second_conditional','What ___ you do if you won?',['would','will','do','are'],'would','Question form 2nd conditional.','What would + subject + base.'],
];
const b1d1_es = [
  ['present_perfect','Write about your experiences (4 sentences with present perfect).','I have traveled to five countries. I have never eaten frog legs. I have learned two languages. I have lived in three cities.','Use have/has + participle.','ever, never, yet, already.'],
  ['first_conditional','Write 4 first conditional sentences about tomorrow.','If it is sunny, I will go to the beach. If I finish early, I will call you. If it rains, I will stay home. If I have time, I will cook dinner.','Use if + present, will.','real future conditions.'],
  ['second_conditional','Write 4 imaginary situations.','If I had a million dollars, I would buy a house. If I were president, I would help the poor. If I could fly, I would travel the world. If I knew her number, I would call.','Use if + past, would + base.','Hypothetical/imaginary.'],
  ['passive_voice','Describe a process in 4 passive sentences.','The coffee beans are picked. They are roasted carefully. They are ground into powder. The coffee is then served.','Use passive voice.','be + past participle.'],
  ['reported_speech','Rewrite 4 statements in reported speech.','She said she was tired. He told me he would come. They said they had finished. She said she liked it.','Apply tense backshift.','is -> was, will -> would.'],
  ['phrasal_verbs','Write 4 sentences with phrasal verbs.','I get up at 6 every day. Please turn off the lights. She looks after her sister. I ran into an old friend.','Use common phrasal verbs.','get up, turn off, look after, run into.'],
  ['modal_verbs','Write 4 sentences about rules and possibilities.','You must wear a helmet. You may not enter here. It might rain tomorrow. You should try this.','Use various modals.','must, may, might, should.'],
  ['linking_words','Write a paragraph using at least 3 linking words (4 sentences).','I wanted to go out; however, I was tired. Moreover, it was raining. Therefore, I stayed home. Finally, I read a book.','Use however, therefore, moreover.','formal linkers.'],
];
b1d1_mc.forEach(a=>rows.push(MC('B1',1,...a)));
b1d1_es.forEach(a=>rows.push(ES('B1',1,...a)));

// B1 D2
const b1d2_mc = [
  ['present_perfect_continuous','I ___ studying for 2 hours.',['have been','has been','am','had been'],'have been','Ongoing action.','have/has been + ing.'],
  ['present_perfect_continuous','She ___ working here since May.',['has been','have been','is','was'],'has been','3rd person ongoing.','has been + ing.'],
  ['third_conditional','If I ___ known, I would have helped.',['had','have','would','did'],'had','3rd conditional: had + participle.','if + past perfect, would have + participle.'],
  ['third_conditional','She ___ passed if she had studied.',['would have','will have','would','had'],'would have','Unreal past.','would have + participle.'],
  ['passive_voice','The project ___ finished next month.',['will be','will','is','has'],'will be','Future passive.','will be + participle.'],
  ['reported_speech','She asked me if I ___ her.',['knew','know','had known','would know'],'knew','know -> knew in reported.','present -> past in reported questions.'],
  ['phrasal_verbs','I cannot ___ up with this noise.',['put','make','take','stand'],'put','put up with = tolerate.','put up with = tolerate.'],
  ['phrasal_verbs','She ___ off the meeting.',['called','made','took','put'],'called','call off = cancel.','call off = cancel.'],
  ['relative_clauses','This is the teacher ___ son plays football.',['whose','who','which','that'],'whose','possession: whose.','whose = possessive relative.'],
  ['relative_clauses','2020 was the year ___ everything changed.',['when','where','which','who'],'when','when for times.','when = in which time.'],
  ['modal_verbs','You ___ have told me earlier!',['should','must','will','can'],'should','Past criticism.','should have + participle.'],
  ['modal_verbs','He ___ be at home; the lights are on.',['must','can','may not','will'],'must','Strong deduction.','must = almost certain.'],
  ['linking_words','He is smart; ___, he is kind.',['moreover','but','because','however'],'moreover','Addition.','moreover = in addition.'],
  ['linking_words','She studied hard; ___, she passed.',['therefore','however','but','although'],'therefore','Consequence.','therefore = as a result.'],
  ['present_perfect','I have ___ been to Asia.',['never','ever','yet','still'],'never','never + participle.','never = not ever.'],
  ['first_conditional','If you do not hurry, you ___ miss the train.',['will','would','are','do'],'will','Real future consequence.','will + base verb.'],
  ['second_conditional','If I ___ you, I would accept.',['were','was','am','be'],'were','Formal 2nd conditional.','If I were you...'],
  ['passive_voice','The car ___ repaired yesterday.',['was','is','has','had'],'was','Past passive.','was + participle.'],
  ['reported_speech','She said, "I can swim." -> She said she ___ swim.',['could','can','would','may'],'could','can -> could.','can becomes could.'],
  ['phrasal_verbs','The meeting ___ at 10.',['starts off','turns off','falls off','runs off'],'starts off','start off = begin.','start off = begin.'],
  ['relative_clauses','The woman, ___ lives upstairs, is nice.',['who','which','whose','that'],'who','Non-defining for people.','use who with commas for people.'],
  ['modal_verbs','You ___ not tell lies.',['should','must','will','can'],'should','should not = advice.','shouldn''t = negative advice.'],
  ['present_perfect_continuous','How long ___ you been waiting?',['have','has','are','did'],'have','you + have been.','How long + have/has + been + ing.'],
  ['third_conditional','I ___ have come if I had known.',['would','will','can','had'],'would','Unreal past result.','would have + participle.'],
  ['passive_voice','This house ___ built in 1920.',['was','is','has','had'],'was','Past simple passive.','was/were + participle.'],
  ['reported_speech','He asked ___ I was okay.',['if','that','what','when'],'if','yes/no reported question.','if/whether for yes/no.'],
  ['phrasal_verbs','The plane ___ off on time.',['took','made','put','got'],'took','take off = depart (plane).','planes take off.'],
  ['relative_clauses','I remember the day ___ we met.',['when','where','which','whose'],'when','Time: when.','when for specific time.'],
  ['modal_verbs','You ___ not do it if you do not want.',['have to','must','should','can'],'have to','not have to = no obligation.','do not have to = optional.'],
  ['linking_words','___ the rain, we went out.',['Despite','Although','Because','Since'],'Despite','despite + noun.','despite/in spite of + noun.'],
  ['linking_words','___ it was raining, we went out.',['Although','Despite','Because','So'],'Although','although + clause.','although + subject + verb.'],
  ['phrasal_verbs','I ran ___ of money.',['out','off','over','up'],'out','run out of = finish.','run out of = deplete.'],
];
const b1d2_es = [
  ['present_perfect_continuous','Describe recent activities (4 sentences).','I have been studying English for a year. She has been working late. We have been traveling a lot. They have been exercising more.','Use have/has been + ing.','ongoing recent actions.'],
  ['third_conditional','Write 4 sentences about regrets.','If I had studied more, I would have passed. If I had woken up earlier, I would not have missed it. If I had saved money, I would have bought it. If I had known, I would have helped.','Use 3rd conditional.','regrets: had + participle, would have + participle.'],
  ['passive_voice','Describe how something is made (4 passive sentences).','The flour is mixed with water. The dough is kneaded. It is left to rise. Then it is baked in the oven.','Sequence with passive.','each step in passive.'],
  ['reported_speech','Rewrite 4 dialogues in reported speech.','She said she would call. He told me he had finished. They said they were leaving. She asked if I was okay.','Apply proper backshift.','said/told + backshift tenses.'],
  ['phrasal_verbs','Write 4 sentences with separable phrasal verbs.','I turned off the TV. She looked up the word. He gave away his old books. Please pick up the phone.','Use common phrasal verbs.','separable: verb + object + particle.'],
  ['modal_verbs','Write 4 sentences expressing different degrees of certainty.','He must be home, his car is there. She might be tired. They cannot be serious. It could rain later.','Use must/might/cannot/could.','deduction/possibility modals.'],
  ['linking_words','Write a paragraph using despite, however, therefore, moreover (4 sentences).','Despite the bad weather, we enjoyed the trip. However, the hotel was uncomfortable. Moreover, the food was cold. Therefore, we will not return.','Use advanced connectors.','formal linking words.'],
  ['relative_clauses','Describe 4 people/places with relative clauses.','This is the house where I grew up. She is the woman who helped me. That is the book which changed my life. He is the friend whose advice I trust.','Use who/which/where/whose.','relative pronouns.'],
];
b1d2_mc.forEach(a=>rows.push(MC('B1',2,...a)));
b1d2_es.forEach(a=>rows.push(ES('B1',2,...a)));

// B1 D3
const b1d3_mc = [
  ['present_perfect_continuous','It ___ raining all day.',['has been','have been','is','was'],'has been','it + has been + ing.','weather: it has been.'],
  ['third_conditional','If he ___ harder, he would have succeeded.',['had worked','worked','has worked','would work'],'had worked','if + past perfect.','past perfect in if-clause.'],
  ['mixed','If I had studied medicine, I ___ a doctor now.',['would be','would have been','will be','was'],'would be','Mixed conditional.','past cause -> present result.'],
  ['passive_voice','The proposal ___ by the committee.',['has been approved','approved','approves','is approving'],'has been approved','Present perfect passive.','has/have been + participle.'],
  ['reported_speech','He told me he ___ the day before.',['had arrived','arrived','has arrived','was arriving'],'had arrived','Backshift past -> past perfect.','past simple -> past perfect.'],
  ['phrasal_verbs','Please ___ with what you are saying.',['go on','go off','go over','go up'],'go on','go on = continue.','go on = continue.'],
  ['phrasal_verbs','The thief ___ away with the money.',['got','made','put','gave'],'got','get away with = escape consequences.','get away with = escape.'],
  ['relative_clauses','The reason ___ I called is urgent.',['why','which','that','where'],'why','reason + why.','why for reason.'],
  ['relative_clauses','Everything ___ glitters is not gold.',['that','who','whose','where'],'that','that after everything.','that after all/everything.'],
  ['modal_verbs','He ___ have forgotten; it is possible.',['may','must','should','can'],'may','may = possibility.','may + have + participle = past possibility.'],
  ['modal_verbs','You needn''t ___ so early.',['have come','come','came','coming'],'have come','needn''t have + participle.','unnecessary past action.'],
  ['linking_words','___ he was tired, he kept working.',['Even though','Despite','Because','So'],'Even though','concession.','even though = although stronger.'],
  ['linking_words','She will succeed, ___ she keeps trying.',['as long as','unless','if not','while'],'as long as','conditional linker.','as long as = provided that.'],
  ['first_conditional','We will go ___ the weather is nice.',['as long as','unless','if not','while'],'as long as','condition for positive.','as long as + present.'],
  ['second_conditional','If I ___ in your position, I would resign.',['were','am','was','be'],'were','subjunctive-like were.','If I were + noun phrase.'],
  ['passive_voice','The letter ___ being written right now.',['is','are','has','was'],'is','Present continuous passive.','is/are being + participle.'],
  ['reported_speech','She asked what time it ___.',['was','is','were','had been'],'was','backshift present -> past.','indirect questions use statement order.'],
  ['phrasal_verbs','I had to ___ down my old computer.',['throw','take','turn','get'],'throw','throw away/out = discard.','throw away = discard.'],
  ['relative_clauses','Paris, ___ I visited last year, is beautiful.',['which','where','that','who'],'which','Non-defining + things.','commas with non-defining.'],
  ['modal_verbs','You ___ have told me; I already knew.',['needn''t','mustn''t','shouldn''t','couldn''t'],'needn''t','unnecessary action.','needn''t have = was unnecessary.'],
  ['present_perfect','I ___ seen that movie three times.',['have','has','am','had'],'have','repeated experience.','three times + present perfect.'],
  ['phrasal_verbs','Can you ___ me back later?',['call','get','put','take'],'call','call back = return call.','call back.'],
  ['phrasal_verbs','She ___ up smoking last year.',['gave','took','put','made'],'gave','give up = quit.','give up = stop habit.'],
  ['linking_words','He studied hard. ___, he failed.',['Nevertheless','Therefore','So','Moreover'],'Nevertheless','strong contrast.','nevertheless = however formal.'],
  ['linking_words','___ he earned, he could save more.',['The more','More','Most','The most'],'The more','the more...the more.','the more + adj, the more + clause.'],
  ['third_conditional','They would have won ___ they had trained harder.',['if','unless','when','as'],'if','if clause.','if + past perfect.'],
  ['modal_verbs','I ___ see the doctor tomorrow; I am not sure.',['might','must','should','will'],'might','uncertainty.','might = uncertain future.'],
  ['reported_speech','He said he ___ working tomorrow.',['would be','will be','is','was'],'would be','will -> would.','will -> would in reported speech.'],
  ['passive_voice','The tickets ___ by now.',['should have been bought','should buy','should be bought','should buys'],'should have been bought','perfect passive with modal.','should have been + participle.'],
  ['present_perfect_continuous','She is exhausted; she ___ all night.',['has been studying','has studied','is studying','studies'],'has been studying','Emphasizing duration and activity.','been + ing for emphasis.'],
  ['relative_clauses','The house ___ roof is red is ours.',['whose','which','who','that'],'whose','possession.','whose for possession.'],
  ['phrasal_verbs','I look ___ to seeing you.',['forward','up','out','over'],'forward','look forward to + ing.','fixed expression.'],
];
const b1d3_es = [
  ['regrets','Write 4 regrets using 3rd conditional.','If I had saved more money, I would have bought a house. If I had studied harder, I would have passed. If I had known, I would have come. If I had listened, I would not have failed.','Use had + participle, would have + participle.','past regrets.'],
  ['hypothetical','Write 4 mixed conditional sentences.','If I had taken that job, I would be richer now. If I were more careful, I would not have lost my keys. If I spoke Chinese, I would have accepted the offer. If I had children, I would live in the suburbs.','Mix time frames in conditionals.','past cause - present result.'],
  ['passive_voice','Describe historical events in 4 passive sentences.','The pyramids were built thousands of years ago. America was discovered in 1492. The wheel was invented long ago. Electricity was harnessed in the 19th century.','Use past passive.','was/were + participle.'],
  ['reported_speech','Write a dialogue then rewrite it in reported speech (4 sentences).','She said she had been working all day. He told me he would finish soon. She asked if I could help. He said he might come later.','Apply backshift consistently.','had + participle, would, could, might.'],
  ['phrasal_verbs','Write 4 sentences using different phrasal verbs.','I ran into an old friend. She is getting over her flu. We need to put off the meeting. He always makes up excuses.','Use varied phrasal verbs.','run into, get over, put off, make up.'],
  ['opinions','Express opinions with linking words (4 sentences).','In my opinion, technology helps us. However, it can be distracting. Moreover, it affects our health. Therefore, we should use it wisely.','Use however, moreover, therefore.','linking opinion markers.'],
  ['modal_deduction','Write 4 deduction sentences about a mystery.','She must be at work. He cannot be the thief. They might know something. We could have missed a clue.','Use must/cannot/might/could.','deduction modals.'],
  ['relative_clauses','Describe your hometown (4 sentences with relative clauses).','My hometown is a place where people are friendly. The park which I used to visit is still there. The school where I studied is closed now. My neighbor, whose garden is beautiful, is 80.','Use where/which/whose.','relative pronouns.'],
];
b1d3_mc.forEach(a=>rows.push(MC('B1',3,...a)));
b1d3_es.forEach(a=>rows.push(ES('B1',3,...a)));
};
