// Part 4: B2 D1, D2, D3
module.exports = function(rows, MC, ES) {
// B2 D1
const b2d1_mc = [
  ['mixed_conditionals','If I had listened, I ___ in this mess.',['would not be','would not have been','will not be','had not been'],'would not be','Past cause - present result.','mixed: had + part / would + base.'],
  ['mixed_conditionals','If she were organized, she ___ the file.',['would have found','would find','will find','found'],'would have found','Present cause - past result.','mixed: were / would have + part.'],
  ['subjunctive','I suggest that he ___ on time.',['be','is','was','were'],'be','Mandative subjunctive.','suggest/insist + that + base verb.'],
  ['subjunctive','It is essential that she ___ present.',['be','is','was','were'],'be','Subjunctive after essential.','essential that + base.'],
  ['advanced_passive','He is said ___ a genius.',['to be','being','been','to being'],'to be','Passive reporting structure.','subject + be said + to infinitive.'],
  ['advanced_passive','The law ___ to be changed.',['is expected','expected','is expecting','expects'],'is expected','Passive + to + infinitive.','is expected to + base.'],
  ['cleft','___ I really need is a holiday.',['What','That','Which','Who'],'What','What-cleft.','What + subject + verb + is/was.'],
  ['cleft','It was John ___ called.',['who','which','whose','what'],'who','It-cleft with person.','It was X who/that...'],
  ['discourse','___, I would recommend this book.',['On the whole','On whole','In whole','For whole'],'On the whole','discourse marker.','on the whole = in general.'],
  ['discourse','___, the project was a success.',['All in all','All in','In all','For all'],'All in all','summary marker.','all in all = in conclusion.'],
  ['inversion','Never ___ I seen such a view.',['have','had','did','do'],'have','Negative adverb inversion.','negative adverb + auxiliary + subject.'],
  ['inversion','Rarely ___ she late.',['is','has','does','did'],'is','inversion after rarely.','rarely + aux + subject.'],
  ['formal','___ to your letter, we confirm...',['With reference','In reference','By reference','For reference'],'With reference','Formal opening.','with reference to.'],
  ['formal','We ___ you of our decision.',['inform','tell','say','advise'],'inform','Formal verb.','inform = formal tell.'],
  ['complex_vocab','His speech was so ___ that nobody listened.',['tedious','tired','bored','boring'],'tedious','tedious = boring.','tedious = long and dull.'],
  ['complex_vocab','She gave a ___ performance.',['compelling','compelled','compellingly','compel'],'compelling','compelling = captivating.','compelling = gripping.'],
  ['collocation','He ___ a mistake.',['made','did','took','had'],'made','make a mistake.','make/do collocations.'],
  ['collocation','She ___ her homework.',['did','made','took','gave'],'did','do homework.','do = tasks, make = create.'],
  ['idioms','It is raining ___ and dogs.',['cats','cat','kittens','pets'],'cats','idiom = heavy rain.','cats and dogs = heavy rain.'],
  ['idioms','Break a ___!',['leg','foot','arm','neck'],'leg','theatrical good luck idiom.','break a leg = good luck.'],
  ['mixed_conditionals','If he ___ harder, he would have a better job.',['studied','had studied','studies','would study'],'studied','present hypothetical -> present result.','if + past simple, would + base.'],
  ['subjunctive','The boss demanded that the report ___ submitted.',['be','is','was','were'],'be','demand + subjunctive.','formal verbs + subjunctive.'],
  ['advanced_passive','The book is thought ___ very influential.',['to be','being','been','to being'],'to be','reporting passive.','to be + adj/noun.'],
  ['cleft','It was in 2020 ___ we moved.',['that','which','when','where'],'that','it-cleft with time: that.','It was X that...'],
  ['discourse','___, let us begin the meeting.',['First of all','First off','First of','In first'],'First of all','sequencing marker.','first of all = to begin.'],
  ['inversion','Hardly ___ I left when it rained.',['had','have','did','was'],'had','hardly...when.','hardly had + subject + participle.'],
  ['formal','Please do not ___ to contact us.',['hesitate','wait','stop','doubt'],'hesitate','do not hesitate to = feel free.','polite closing phrase.'],
  ['complex_vocab','His argument was ___ and convincing.',['coherent','coherently','coherence','cohere'],'coherent','adjective needed.','coherent = logical.'],
  ['collocation','They ___ a plan.',['made','did','took','got'],'made','make a plan.','make a plan.'],
  ['idioms','Under the ___, I feel unwell.',['weather','climate','cloud','sky'],'weather','under the weather = ill.','under the weather = sick.'],
  ['cleft','The reason ___ I came is to help.',['why','which','that','where'],'why','reason + why.','The reason why...'],
  ['inversion','Not only ___ he smart, but also kind.',['is','does','has','was'],'is','Not only inversion.','Not only + aux + subject.'],
];
const b2d1_es = [
  ['mixed_conditionals','Write 3 mixed conditional sentences about your life.','If I had moved abroad, I would speak better English now. If I were more organized, I would have finished yesterday. If I had studied medicine, I would be a doctor today.','Mix time frames.','past->present and present->past.'],
  ['formal_letter','Write 4 sentences as part of a formal email to a company.','I am writing to enquire about your services. Please find my CV attached. I would be grateful if you could respond. I look forward to hearing from you.','Use formal register.','formal salutations and phrasing.'],
  ['opinion','Write a 4-sentence opinion on social media.','Social media has transformed communication. On one hand, it connects people globally. On the other hand, it can harm mental health. Overall, we must use it mindfully.','Use discourse markers.','on one hand, overall.'],
  ['cleft','Write 4 cleft sentences emphasizing different elements.','What I love most is travel. It was my mother who inspired me. The thing that matters most is family. It is here that I feel at home.','Use what-clefts and it-clefts.','cleft structures.'],
  ['advanced_passive','Report news using advanced passives (4 sentences).','The minister is reported to have resigned. The treaty is believed to have failed. The suspect is said to be in hiding. The cure is thought to be near.','Use reporting passives.','is said/reported/believed + to.'],
  ['idioms','Write 4 sentences using English idioms.','I am over the moon with the news. Let us call it a day. That was a piece of cake. She hit the nail on the head.','Use common idioms.','over the moon, piece of cake.'],
  ['inversion','Write 4 sentences using inversion for emphasis.','Never have I seen such kindness. Rarely does he complain. Not only is she smart, but also funny. Little did I know what was coming.','Use negative adverb inversion.','never/rarely/not only + aux.'],
  ['collocations','Write 4 sentences with make/do/have/take collocations.','I need to make a decision. She always does her best. We had a great time. Let us take a break.','Use natural collocations.','make/do/take/have patterns.'],
];
b2d1_mc.forEach(a=>rows.push(MC('B2',1,...a)));
b2d1_es.forEach(a=>rows.push(ES('B2',1,...a)));

// B2 D2
const b2d2_mc = [
  ['mixed_conditionals','If I ___ more patient, I would not have shouted.',['had been','were','was','am'],'had been','Mixed: past hypothetical condition.','past perfect + would have.'],
  ['subjunctive','She insisted that he ___ the truth.',['tell','tells','told','telling'],'tell','insist + that + base.','mandative subjunctive.'],
  ['advanced_passive','The new policy ___ into effect tomorrow.',['will be put','will put','is put','is putting'],'will be put','future passive.','will be + participle.'],
  ['cleft','It was her courage ___ impressed us.',['that','who','which','where'],'that','it-cleft with noun.','It was X that + verb.'],
  ['discourse','___, let me address the main issue.',['That said','That say','To say','Saying'],'That said','discourse marker for transition.','that said = having said that.'],
  ['inversion','Only then ___ I realize the truth.',['did','had','have','was'],'did','only + adverb inversion.','only + aux + subject.'],
  ['formal','We regret ___ you that your application was unsuccessful.',['to inform','informing','inform','to informing'],'to inform','regret + to inf (bad news).','regret to + base.'],
  ['complex_vocab','The evidence is ___ of his guilt.',['indicative','indicating','indication','indicate'],'indicative','adjective for noun.','indicative of = showing.'],
  ['collocation','She ___ a deep breath.',['took','made','did','had'],'took','take a breath.','take a breath.'],
  ['idioms','It costs an arm and a ___.',['leg','foot','hand','head'],'leg','idiom = very expensive.','arm and a leg = pricey.'],
  ['mixed_conditionals','If you had been kinder, she ___ you now.',['would trust','would have trusted','will trust','trusts'],'would trust','past cause, present effect.','had been + would + base.'],
  ['subjunctive','It is important that everyone ___ on time.',['arrive','arrives','arrived','arriving'],'arrive','important that + base.','impersonal + subjunctive.'],
  ['advanced_passive','The issue ___ being discussed at the moment.',['is','are','has','was'],'is','present continuous passive.','is being + participle.'],
  ['cleft','What ___ most is honesty.',['matters','matter','mattering','mattered'],'matters','what + singular verb.','what subject + singular verb.'],
  ['discourse','___ from that, I agree with you.',['Apart','Except','Aside','Besides'],'Apart','apart from = except.','apart from + noun.'],
  ['inversion','Scarcely ___ the bell rung when the kids ran.',['had','have','did','was'],'had','scarcely...when.','scarcely had + participle + when.'],
  ['formal','I am writing with ___ to your enquiry.',['regard','regards','regarding','regarded'],'regard','with regard to = regarding.','formal phrase.'],
  ['complex_vocab','His explanation was rather ___.',['ambiguous','ambiguity','ambiguously','ambiguate'],'ambiguous','adjective needed.','ambiguous = unclear.'],
  ['collocation','She ___ a shower every morning.',['has','makes','does','takes'],'has','have/take a shower.','have or take a shower.'],
  ['idioms','Let the cat out of the ___.',['bag','box','sack','house'],'bag','let the cat out of the bag = reveal secret.','common idiom.'],
  ['mixed_conditionals','If he were not so lazy, he ___ the test.',['would have passed','would pass','passed','had passed'],'would have passed','present trait, past result.','were + would have + part.'],
  ['subjunctive','I wish I ___ younger.',['were','was','am','be'],'were','wish + were (formal).','wish + past subjunctive.'],
  ['advanced_passive','They are believed ___ the bank.',['to have robbed','to rob','robbing','robbed'],'to have robbed','perfect infinitive passive.','to have + participle.'],
  ['cleft','It is because of you ___ I am here.',['that','who','which','what'],'that','it-cleft reason.','It is because...that.'],
  ['discourse','___ to popular belief, the Earth is not flat.',['Contrary','Contrast','Contraction','Counter'],'Contrary','contrary to = opposite of.','contrary to + noun.'],
  ['inversion','Under no circumstances ___ you enter.',['should','must','can','will'],'should','inversion after under no.','under no circumstances + modal + subject.'],
  ['formal','Should you ___ questions, please call.',['have','having','had','to have'],'have','inverted conditional.','should + subject + base = if.'],
  ['complex_vocab','His answer was quite ___.',['vague','vaguely','vagueness','vague'],'vague','adjective.','vague = unclear.'],
  ['collocation','They ___ a conclusion.',['reached','made','took','had'],'reached','reach a conclusion.','reach = arrive at.'],
  ['idioms','Once in a blue ___.',['moon','day','year','time'],'moon','rare event.','once in a blue moon = rarely.'],
  ['idioms','The early bird catches the ___.',['worm','bird','food','prize'],'worm','idiom about being early.','early bird idiom.'],
  ['complex_vocab','The data is ___ to support the claim.',['insufficient','insufficiency','insufficiently','sufficient'],'insufficient','adjective.','insufficient = not enough.'],
];
const b2d2_es = [
  ['formal_email','Write a 4-sentence complaint email to a company.','I am writing to express my dissatisfaction with your service. The product arrived damaged despite careful handling. I would appreciate a full refund at your earliest convenience. I trust this matter will be resolved promptly.','Use formal register and appropriate phrases.','formal complaint patterns.'],
  ['argument','Argue for or against online learning (4 sentences).','While online learning offers flexibility, it lacks human interaction. On one hand, students can study at their own pace. On the other hand, motivation becomes a challenge. Overall, a hybrid approach seems optimal.','Use discourse markers.','on one hand/other hand, overall.'],
  ['cleft_emphasis','Emphasize different elements (4 cleft sentences).','What surprises me most is his honesty. It was the team that made the difference. The thing I value most is time. It is determination that leads to success.','Use what- and it-clefts.','cleft for emphasis.'],
  ['inversion_style','Write 4 sentences with inversion in formal style.','Little did they know about the changes. Never before have I faced such a challenge. Only by hard work can we succeed. Seldom does she miss a deadline.','Use various inversions.','little/never/only/seldom inversions.'],
  ['mixed_conditional_regrets','Describe 4 mixed regrets.','If I had saved more, I would be wealthier today. If I were not so shy, I would have made more friends. If he had listened to advice, he would not be in trouble now. If she spoke English, she would have got that job.','Mix past and present in conditionals.','past perfect + would + base (present); were + would have + part.'],
  ['subjunctive_usage','Write 4 sentences using subjunctive after suggest, insist, recommend, essential.','The manager suggested that we arrive early. She insisted that he apologize. I recommend that the report be revised. It is essential that everyone attend the meeting.','Use base form in subjunctive.','bare infinitive after mandative verbs.'],
  ['advanced_passive','Rewrite 4 sentences using reporting passives.','The minister is thought to have lied. The company is said to be in trouble. The treaty is believed to have failed. The drug is reported to cause side effects.','Use is thought/said/believed/reported.','reporting structures with passive.'],
  ['idioms_register','Use 4 idioms appropriately in sentences.','That test was a piece of cake. She is under the weather today. He let the cat out of the bag. We are in the same boat.','Use idioms with correct context.','common English idioms.'],
];
b2d2_mc.forEach(a=>rows.push(MC('B2',2,...a)));
b2d2_es.forEach(a=>rows.push(ES('B2',2,...a)));

// B2 D3
const b2d3_mc = [
  ['mixed_conditionals','Were he more careful, he ___ the accident.',['would have avoided','would avoid','had avoided','avoided'],'would have avoided','inverted 2nd + 3rd.','were + subject = if + were.'],
  ['subjunctive','If he ___ here, everything would be easier.',['were','was','is','be'],'were','2nd conditional subjunctive.','if + were for all persons.'],
  ['advanced_passive','The ceremony ___ next week.',['is to be held','is holding','held','is held'],'is to be held','future passive with be to.','be to + passive.'],
  ['cleft','It was not until midnight ___ he arrived.',['that','when','which','what'],'that','it-cleft with not until.','It was not until...that.'],
  ['discourse','___, we had no other option.',['As a matter of fact','In matter','On matter','By matter'],'As a matter of fact','discourse marker.','as a matter of fact = actually.'],
  ['inversion','So tired ___ he that he slept 12 hours.',['was','is','had','did'],'was','inversion after so + adj.','so + adj + aux + subject.'],
  ['formal','In ___ of the circumstances, we will postpone.',['view','sight','regard','light'],'view','in view of = because of.','formal prepositional phrase.'],
  ['complex_vocab','Her argument lacked ___.',['substance','substantial','substantially','substantiate'],'substance','noun after lack.','substance = content/weight.'],
  ['collocation','He ___ a heavy responsibility.',['bears','takes','has','makes'],'bears','bear responsibility.','bear = carry/accept.'],
  ['idioms','She ___ the ice at the party.',['broke','cut','hit','made'],'broke','break the ice.','break the ice = start conversation.'],
  ['mixed_conditionals','Had I known, I ___ differently.',['would have acted','would act','acted','act'],'would have acted','inverted 3rd conditional.','had + subject = if + had.'],
  ['subjunctive','The judge ordered that the defendant ___ silent.',['remain','remains','remained','remaining'],'remain','order + subjunctive.','order that + base.'],
  ['advanced_passive','He is rumoured ___ a millionaire.',['to be','being','been','to being'],'to be','reporting passive.','to be + noun/adj.'],
  ['cleft','All ___ I want is peace.',['that','which','who','what'],'that','all + that.','All that subject + verb + is/was.'],
  ['discourse','___, the results were inconclusive.',['In short','In quick','In brief','Above all'],'In short','summary marker.','in short = briefly.'],
  ['inversion','No sooner ___ we arrived than it started.',['had','did','have','were'],'had','no sooner...than.','no sooner + past perfect.'],
  ['formal','Kindly ___ receipt of this email.',['acknowledge','know','say','reply'],'acknowledge','formal verb.','acknowledge receipt = confirm.'],
  ['complex_vocab','The plan was fundamentally ___.',['flawed','flawlessly','flawlessness','flaw'],'flawed','adjective.','flawed = defective.'],
  ['collocation','Please ___ into consideration my request.',['take','make','put','have'],'take','take into consideration.','take into account/consideration.'],
  ['idioms','He is sitting on the ___.',['fence','chair','wall','floor'],'fence','idiom = undecided.','sit on the fence = neutral.'],
  ['mixed_conditionals','If he had not been ill, he ___ here now.',['would be','would have been','was','is'],'would be','past cause, present result.','mixed conditional.'],
  ['subjunctive','She wishes she ___ taller.',['were','was','is','be'],'were','wish + were.','formal wish with subjunctive.'],
  ['advanced_passive','The problem must ___ immediately.',['be addressed','address','addressing','be addressing'],'be addressed','modal + be + participle.','modal passive.'],
  ['cleft','It is only then ___ I understood.',['that','when','which','what'],'that','it-cleft with only.','It is only X that...'],
  ['discourse','___ clear, I am not happy.',['To be','Being','Been','Be'],'To be','discourse: to be X.','to be clear/honest/fair.'],
  ['inversion','Only after he left ___ I realize.',['did','had','have','was'],'did','only + adverb clause inversion.','only after + clause + aux + subject.'],
  ['formal','We ___ like to apologize for the delay.',['would','will','should','could'],'would','polite formal.','would like = formal want.'],
  ['complex_vocab','Her behavior was ___ to say the least.',['peculiar','peculiarly','peculiarity','peculiar'],'peculiar','adjective.','peculiar = strange.'],
  ['collocation','They ___ pressure on the government.',['put','made','did','took'],'put','put pressure on.','put pressure on = pressure.'],
  ['idioms','He jumped on the ___ quickly.',['bandwagon','train','car','boat'],'bandwagon','idiom = join a trend.','jump on the bandwagon.'],
  ['advanced_passive','The issue should have ___ earlier.',['been raised','been rising','raised','rose'],'been raised','modal perfect passive.','should have been + participle.'],
  ['cleft','It was here ___ we first met.',['that','which','when','what'],'that','it-cleft place.','It was X that + verb.'],
];
const b2d3_es = [
  ['opinion_essay','Write 4 sentences of an opinion essay on technology.','Technology undoubtedly shapes modern life. While it offers unprecedented convenience, it also raises ethical concerns. Moreover, it transforms the workplace at a dizzying pace. Ultimately, we must wield it with wisdom.','Use formal register.','elevated vocabulary.'],
  ['argument_essay','Argue a position with concessions (4 sentences).','Admittedly, remote work has drawbacks such as isolation. Nevertheless, its benefits far outweigh these concerns. Not only does it save commuting time, but it also boosts productivity. In light of this, companies should embrace flexibility.','Use concession + strong argument.','admittedly, nevertheless, not only.'],
  ['formal_report','Write the introduction of a formal report (4 sentences).','This report examines the impact of remote work on productivity. Data was collected from 500 employees across three sectors. The findings are presented in three sections. Recommendations are outlined at the end.','Use passive and formal tone.','passive voice and headings.'],
  ['inversion_advanced','Write 4 sentences with advanced inversion.','Not only had he lied, but he had also stolen. Hardly had the meeting started when the fire alarm rang. Under no circumstances should you share the password. Little did she realize how much he cared.','Use varied inversions.','negative adverbs triggering inversion.'],
  ['idioms_advanced','Use 4 advanced idioms in context.','He threw in the towel after the third attempt. She hit the nail on the head with her analysis. They are skating on thin ice financially. It is time to face the music.','Use idioms naturally.','throw in the towel, face the music.'],
  ['cleft_emphasis','Write 4 complex cleft sentences for emphasis.','What strikes me most is the complexity. It was only after years of work that she succeeded. The reason why we failed is lack of planning. All that we need is more time.','Use varied cleft structures.','what, it, reason, all + cleft.'],
  ['subjunctive_formal','Write 4 formal sentences using subjunctive.','The committee recommended that the proposal be rejected. It is imperative that he attend the meeting. The law requires that every vehicle be insured. I suggest he apply immediately.','Use bare infinitive.','formal mandative subjunctive.'],
  ['collocation_register','Use 4 formal collocations.','The company has taken considerable steps to improve. We reached a consensus after long debate. The policy has far-reaching implications. They drew a distinction between the two cases.','Use advanced collocations.','take steps, reach consensus, draw distinction.'],
];
b2d3_mc.forEach(a=>rows.push(MC('B2',3,...a)));
b2d3_es.forEach(a=>rows.push(ES('B2',3,...a)));
};
