// Part 5: C1 D1, D2, D3
module.exports = function(rows, MC, ES) {
// C1 D1
const c1d1_mc = [
  ['advanced_inversion','Not until later ___ the full extent of the damage apparent.',['did','was','had','became'],'did','inversion after not until.','not until + aux + subject + verb.'],
  ['cleft','It was his persistence ___ ultimately prevailed.',['that','which','who','what'],'that','it-cleft formal.','It was X that + verb.'],
  ['academic_vocab','The study aims to ___ the relationship between variables.',['elucidate','elude','allude','include'],'elucidate','elucidate = clarify.','elucidate = explain.'],
  ['academic_vocab','The findings ___ our hypothesis.',['corroborate','collaborate','correlate','cooperate'],'corroborate','corroborate = support.','corroborate = confirm evidence.'],
  ['hedging','The data ___ a trend.',['suggests','proves','demonstrates','shows'],'suggests','hedged verb.','suggest = soften claim.'],
  ['hedging','This may ___ be due to chance.',['well','good','very','too'],'well','may well = likely.','may well = probably.'],
  ['complex_syntax','Having completed the task, ___ relaxed.',['they','he had','she was','we were'],'they','participle phrase + subject.','participle phrase + subject clause.'],
  ['complex_syntax','Given the circumstances, ___ the best option.',['this seems','it is seeming','being','to be'],'this seems','given + noun + independent clause.','given + noun = considering.'],
  ['nominalization','The ___ of the project was delayed.',['completion','completing','complete','completed'],'completion','noun form.','nominalization: verb -> noun.'],
  ['nominalization','His ___ was well received.',['explanation','explain','explained','explaining'],'explanation','noun.','explanation (noun) vs explain (verb).'],
  ['advanced_collocations','They made a ___ effort.',['concerted','concert','concerning','concerned'],'concerted','concerted effort = joint.','concerted = coordinated.'],
  ['advanced_collocations','The issue raised ___ concerns.',['serious','series','seriously','seriousness'],'serious','serious concerns.','serious + noun.'],
  ['register','The aforementioned ___ must be reviewed.',['documents','document','documenting','documented'],'documents','formal register noun plural.','aforementioned = previously mentioned.'],
  ['register','She ___ assistance with the task.',['requires','needs','wants','asks'],'requires','formal register.','require = formal need.'],
  ['reported_speech_complex','He claimed he ___ the contract long before.',['had signed','signed','has signed','would sign'],'had signed','backshift past -> past perfect.','past perfect in reported speech.'],
  ['reported_speech_complex','She denied ___ the email.',['sending','to send','send','sent'],'sending','deny + gerund.','deny + ing.'],
  ['subjunctive_advanced','Be that ___ it may, I disagree.',['as','so','that','which'],'as','be that as it may = however.','fixed subjunctive expression.'],
  ['subjunctive_advanced','Suffice ___ to say, we succeeded.',['it','that','so','as'],'it','suffice it to say = enough to say.','fixed expression.'],
  ['academic_vocab','The results ___ our predictions.',['align with','align to','align at','align for'],'align with','align with = match.','align with = agree.'],
  ['hedging','It is ___ possible that the theory is flawed.',['quite','too','much','very'],'quite','quite possible = moderately likely.','quite + adjective for hedging.'],
  ['complex_syntax','Not only ___ she intelligent, but also diligent.',['is','was','has','does'],'is','inversion with not only.','not only + aux + subject.'],
  ['nominalization','The government''s ___ of the issue was criticized.',['handling','handle','handled','hand'],'handling','noun form.','handle -> handling.'],
  ['advanced_collocations','The research ___ ground-breaking insights.',['yielded','took','made','had'],'yielded','yield insights/results.','yield = produce.'],
  ['register','We would be grateful ___ you could confirm.',['if','that','when','so'],'if','formal conditional.','we would be grateful if.'],
  ['reported_speech_complex','He admitted to ___ the money.',['taking','take','took','taken'],'taking','admit to + gerund.','admit + ing.'],
  ['subjunctive_advanced','God ___ the Queen.',['save','saves','saved','saving'],'save','formulaic subjunctive.','May God save (formal).'],
  ['academic_vocab','The term refers ___ the process of change.',['to','at','on','for'],'to','refer to.','refer to = mean.'],
  ['hedging','It ___ appear that the data is incomplete.',['would','will','should','shall'],'would','would appear = softer.','hedged with would.'],
  ['complex_syntax','Such ___ the complexity that experts disagreed.',['was','is','did','had'],'was','such + inversion.','such + be + noun + that.'],
  ['nominalization','The company''s ___ strategy is effective.',['pricing','priced','price','prices'],'pricing','gerund as noun.','pricing as noun/adj.'],
  ['advanced_collocations','They need to ___ a compromise.',['strike','make','do','take'],'strike','strike a compromise/deal.','strike = reach.'],
  ['register','We ___ the opportunity to thank you.',['take','make','do','have'],'take','take the opportunity (formal).','take this opportunity.'],
];
const c1d1_es = [
  ['academic_essay','Write an academic introduction (4 sentences).','This paper examines the effects of globalization on local cultures. Drawing on recent research, it identifies three main patterns. It argues that cultural homogenization is less inevitable than often assumed. The implications for policy are considered in the conclusion.','Use academic register.','academic tone and structure.'],
  ['hedging','Write 4 hedged statements about a study.','The evidence suggests a correlation between variables. It appears that other factors may be at play. These findings would seem to support the theory. Further research is arguably needed.','Use tentative language.','suggest, appear, may, arguably.'],
  ['complex_syntax','Use 4 complex sentence structures.','Having considered the options, we opted for the hybrid approach. Given the circumstances, this seems reasonable. Such was his influence that policy changed. Not only did she lead, but she also inspired.','Use participles, inversions, given + noun.','varied complex structures.'],
  ['nominalization','Rewrite 4 verbs as nominalized structures.','The implementation of the policy was difficult. The failure of the system was catastrophic. The expansion of the market is ongoing. The rejection of the proposal was expected.','Transform verbs to nouns.','implement->implementation, fail->failure.'],
  ['formal_register','Write 4 sentences in highly formal register.','We would be most grateful for your prompt attention to this matter. Further details may be provided upon request. Should you have any queries, please do not hesitate to contact us. We appreciate your continued support.','Use formal collocations.','would be grateful, should you have.'],
  ['reported_speech_advanced','Report 4 statements with advanced structures.','She admitted to having made the error. He denied any involvement in the scheme. The committee acknowledged that reforms were needed. The witness confirmed having seen the incident.','Use reporting verbs + structures.','admit/deny + gerund/noun.'],
  ['cleft_emphasis','Use cleft sentences to emphasize (4 sentences).','It is precisely this approach that distinguishes our method. What ultimately matters is the long-term impact. The fundamental issue is one of trust. All that remains is to reach consensus.','Use varied cleft structures.','it is, what, the Y is, all that.'],
  ['academic_vocab','Use 4 academic vocabulary items in sentences.','The findings corroborate previous research. The data elucidates a complex relationship. The methodology aligns with standard practice. The conclusions warrant further investigation.','Use elevated vocabulary.','corroborate, elucidate, align, warrant.'],
];
c1d1_mc.forEach(a=>rows.push(MC('C1',1,...a)));
c1d1_es.forEach(a=>rows.push(ES('C1',1,...a)));

// C1 D2
const c1d2_mc = [
  ['advanced_inversion','Little ___ he imagine what awaited him.',['did','had','was','would'],'did','little + aux + subject.','little + do/did/does.'],
  ['cleft','What ___ us is her refusal to compromise.',['puzzles','puzzle','puzzling','puzzled'],'puzzles','what + singular verb.','what-cleft: what + verb.'],
  ['academic_vocab','This phenomenon ___ several disciplines.',['transcends','transgresses','transforms','transports'],'transcends','transcend = go beyond.','transcend = surpass.'],
  ['academic_vocab','The results ___ a clear pattern.',['delineate','deliberate','delegate','delight'],'delineate','delineate = describe/outline.','delineate = map out.'],
  ['hedging','It ___ argued that the theory holds.',['could be','can','may','might'],'could be','could be argued (hedged).','passive hedging.'],
  ['hedging','The figures ___ to indicate growth.',['seem','seems','seeming','seemed'],'seem','plural subject.','seem + to + base.'],
  ['complex_syntax','No sooner ___ he arrived than the phone rang.',['had','did','was','has'],'had','no sooner had + participle.','no sooner...than inversion.'],
  ['complex_syntax','Were the situation ___, we would reconsider.',['different','differently','difference','differ'],'different','were + subject + adj.','were S + adj = if S were adj.'],
  ['nominalization','The ___ in productivity surprised analysts.',['decline','declined','declining','declines'],'decline','noun after the.','the + noun.'],
  ['nominalization','A thorough ___ of the problem is needed.',['investigation','investigate','investigating','investigator'],'investigation','noun.','investigation (process noun).'],
  ['advanced_collocations','The government ___ reforms.',['implemented','made','did','took'],'implemented','implement reforms.','implement = put into effect.'],
  ['advanced_collocations','They ___ doubt on the findings.',['cast','put','threw','made'],'cast','cast doubt on.','cast doubt = question.'],
  ['register','___ the regulations, smoking is prohibited.',['Per','By','In','On'],'Per','per = according to (formal).','per + noun.'],
  ['register','We ___ to differ on this point.',['agree','accept','admit','allow'],'agree','formal: agree to differ.','idiomatic formal phrase.'],
  ['reported_speech_complex','She suggested ___ a different approach.',['taking','to take','take','taken'],'taking','suggest + gerund.','suggest + ing.'],
  ['reported_speech_complex','He accused her ___ lying.',['of','for','to','about'],'of','accuse of + gerund.','accuse someone of + ing.'],
  ['subjunctive_advanced','Were I in your position, I ___ differently.',['would act','would have acted','act','will act'],'would act','inverted 2nd conditional.','were + subject = if + were.'],
  ['subjunctive_advanced','Had he known, he ___ otherwise.',['would have acted','would act','had acted','acted'],'would have acted','inverted 3rd conditional.','had + subject = if had.'],
  ['academic_vocab','This approach has considerable ___.',['merit','merits','meritorious','merited'],'merit','noun.','merit = worth.'],
  ['hedging','One could ___ that this is untrue.',['argue','say','tell','speak'],'argue','one could argue (hedged).','impersonal hedge.'],
  ['complex_syntax','So ___ was his speech that all were silent.',['compelling','compel','compels','compelled'],'compelling','so + adj inversion.','so + adj + aux + subject.'],
  ['nominalization','The ___ of evidence is concerning.',['scarcity','scarce','scarcely','scarceness'],'scarcity','noun.','scarce -> scarcity.'],
  ['advanced_collocations','We need to ___ a decision.',['reach','make','do','have'],'reach','reach a decision.','reach = arrive at.'],
  ['register','Please ___ attention to the enclosed documents.',['draw','take','pay','give'],'draw','draw attention to.','draw attention = highlight.'],
  ['reported_speech_complex','He warned me ___ the road.',['against crossing','to cross','of crossing','from cross'],'against crossing','warn against + ing.','warn against + ing.'],
  ['subjunctive_advanced','Long ___ the King!',['live','lives','lived','living'],'live','subjunctive wish.','may + base = long live.'],
  ['academic_vocab','The research ___ several limitations.',['acknowledges','acknowledged','acknowledgement','acknowledge'],'acknowledges','3rd person verb.','research + s.'],
  ['hedging','These figures ___ an upward trend.',['would suggest','will suggest','suggest','suggesting'],'would suggest','hedged.','would + suggest for tentativeness.'],
  ['complex_syntax','Such was the ___ that everyone applauded.',['brilliance','brilliant','brilliantly','brilliance'],'brilliance','noun after such.','such + noun + that.'],
  ['nominalization','The ___ of the theory is challenged.',['validity','valid','validly','validate'],'validity','noun.','valid -> validity.'],
  ['advanced_collocations','They have ___ considerable progress.',['made','took','did','had'],'made','make progress.','make progress.'],
  ['register','We ___ the receipt of your payment.',['acknowledge','know','accept','admit'],'acknowledge','formal confirmation.','acknowledge receipt.'],
];
const c1d2_es = [
  ['academic_argument','Present an academic argument (4 sentences).','This essay contends that urbanization poses significant challenges to sustainability. While recognizing its economic benefits, the analysis highlights environmental costs. Drawing on empirical data, three key issues emerge. The paper concludes with policy recommendations.','Use academic register.','contend, highlight, conclude.'],
  ['hedging_advanced','Write 4 hedged statements.','The data could be interpreted to suggest a correlation. It would appear that external factors play a role. The findings are, arguably, preliminary. One might reasonably argue that further study is warranted.','Use sophisticated hedging.','could be, would appear, arguably.'],
  ['nominalization','Rewrite 4 sentences using nominalization.','The deterioration of infrastructure is alarming. The expansion of services is underway. The rejection of the proposal surprised many. The reorganization of the department was successful.','Use abstract nouns.','deteriorate -> deterioration.'],
  ['complex_syntax','Write 4 sentences with complex structures.','Not only did the strategy succeed, but it also exceeded expectations. Were this approach adopted, substantial savings would follow. Scarcely had the report been released when it was criticized. Such was the public outcry that policy changed.','Use inversions and complex forms.','not only, were, scarcely, such was.'],
  ['academic_register','Write 4 sentences with academic register.','The present study investigates the implications of the proposed reform. Our findings align with prior research, yet diverge in key respects. These outcomes warrant further investigation. We therefore recommend a comprehensive review.','Use formal academic style.','investigates, align, diverge, warrant.'],
  ['reported_speech_advanced','Use 4 advanced reporting structures.','She is reported to have accepted the position. He is alleged to have falsified the records. The committee is understood to be divided. The minister is believed to have resigned.','Use passive reporting.','is reported/alleged/understood/believed.'],
  ['cleft_advanced','Use 4 advanced cleft structures.','It was her unwavering commitment that inspired the team. What proved decisive was the timing of the announcement. The very essence of the argument is its simplicity. All that remains is to ratify the agreement.','Use varied clefts.','it was, what, the very, all that.'],
  ['formal_letter','Write 4 sentences of a formal business letter.','I trust this letter finds you well. I am writing to propose a partnership between our organizations. Should this proposal be of interest, I would welcome a meeting. I look forward to your considered response.','Use formal business style.','trust, propose, should, welcome.'],
];
c1d2_mc.forEach(a=>rows.push(MC('C1',2,...a)));
c1d2_es.forEach(a=>rows.push(ES('C1',2,...a)));

// C1 D3
const c1d3_mc = [
  ['advanced_inversion','On no ___ should this be disclosed.',['account','accounts','accounted','accountable'],'account','on no account = never.','formal negative adverbial.'],
  ['cleft','It is ___ his dedication that the project succeeded.',['owing to','owing','owe to','owed'],'owing to','owing to = because of.','formal causal preposition.'],
  ['academic_vocab','The hypothesis was ___ by new data.',['refuted','refused','refunded','referred'],'refuted','refute = disprove.','refute = prove false.'],
  ['academic_vocab','The study ___ previous findings.',['builds on','builds in','builds at','builds to'],'builds on','build on = develop from.','build on = extend.'],
  ['hedging','This ___ not necessarily hold in all cases.',['does','will','is','can'],'does','modal hedging.','does + not + necessarily.'],
  ['hedging','The evidence is, ___, inconclusive.',['at best','at good','at most','at worst'],'at best','at best = optimistically.','at best = most favorably.'],
  ['complex_syntax','So ___ is the problem that urgent action is needed.',['grave','gravely','gravity','graveness'],'grave','adjective after so.','so + adj + be + subject.'],
  ['complex_syntax','___ convinced was she that she refused to listen.',['So','Such','Very','That'],'So','so + adj inversion.','so + adj + be + subject + that.'],
  ['nominalization','The ___ of responsibilities was unclear.',['delineation','delineate','delineated','delineating'],'delineation','abstract noun.','delineate -> delineation.'],
  ['nominalization','The ___ of the data proved complex.',['interpretation','interpret','interpreted','interpreting'],'interpretation','noun form.','interpret -> interpretation.'],
  ['advanced_collocations','The findings ___ far-reaching implications.',['carry','make','do','take'],'carry','carry implications.','carry = have.'],
  ['advanced_collocations','Her argument ___ weight with the panel.',['carried','made','did','took'],'carried','carry weight = be persuasive.','carry weight = be influential.'],
  ['register','We trust this ___ your requirements.',['meets','makes','does','has'],'meets','formal verb.','meet requirements.'],
  ['register','Please find ___ the documents requested.',['enclosed','closed','included','added'],'enclosed','please find enclosed (formal).','formal letter phrase.'],
  ['reported_speech_complex','She is said ___ considerable expertise.',['to possess','possessing','possess','possessed'],'to possess','reporting passive.','subject + be said + to + base.'],
  ['reported_speech_complex','He is thought ___ for years.',['to have worked','to work','working','worked'],'to have worked','perfect infinitive reporting.','to have + participle.'],
  ['subjunctive_advanced','It is crucial that the committee ___ the recommendations.',['adopt','adopts','adopted','adopting'],'adopt','mandative subjunctive.','crucial that + base.'],
  ['subjunctive_advanced','He requested that the meeting ___ postponed.',['be','is','was','were'],'be','passive subjunctive.','request that + be + part.'],
  ['academic_vocab','The evidence ___ an alternative explanation.',['warrants','wants','warns','wades'],'warrants','warrant = justify.','warrant = justify.'],
  ['hedging','To some ___, this may be true.',['extent','extend','extends','extension'],'extent','to some extent = partially.','to some extent (hedging).'],
  ['complex_syntax','Nowhere ___ such beauty be found.',['can','could','does','is'],'can','nowhere + aux + subject.','nowhere + modal + subject.'],
  ['nominalization','The ___ of trust takes time.',['restoration','restore','restored','restoring'],'restoration','noun.','restore -> restoration.'],
  ['advanced_collocations','The plan is ___ with challenges.',['fraught','full','filled','fit'],'fraught','fraught with = full of.','fraught = worried/full.'],
  ['advanced_collocations','They ___ with the proposal.',['concur','concurrent','concurrently','concurrence'],'concur','concur = agree.','concur with = agree.'],
  ['register','We ___ your cooperation in this matter.',['appreciate','like','want','ask'],'appreciate','formal expression.','appreciate = thank formally.'],
  ['reported_speech_complex','It was pointed out ___ errors existed.',['that','which','who','where'],'that','pointed out that + clause.','point out that.'],
  ['subjunctive_advanced','The court ordered that he ___ to prison.',['be sent','is sent','was sent','sending'],'be sent','passive subjunctive.','ordered that + be + part.'],
  ['academic_vocab','The paper ___ a novel framework.',['propounds','propels','proposes','presents'],'proposes','propose a framework.','propose = put forward.'],
  ['hedging','The author ___ that the theory is robust.',['maintains','insists','demands','orders'],'maintains','maintain = argue (hedged).','maintain = hold a view.'],
  ['complex_syntax','Only by understanding the past ___ we shape the future.',['can','could','should','do'],'can','only by + ing + aux + subject.','only by...can subject.'],
  ['nominalization','The ___ of resources is problematic.',['allocation','allocate','allocated','allocating'],'allocation','noun.','allocate -> allocation.'],
  ['advanced_collocations','She ___ a compelling case.',['mounted','did','made','had'],'mounted','mount a case = build argument.','mount = construct.'],
];
const c1d3_es = [
  ['dissertation','Write a 4-sentence dissertation abstract.','This dissertation interrogates the intersection of technology and democracy. Employing mixed-methods research, it analyzes data from three national contexts. The findings challenge prevailing assumptions about digital participation. The study concludes by proposing a revised theoretical framework.','Use academic abstract register.','interrogate, employ, challenge, propose.'],
  ['critical_analysis','Write a critical analysis (4 sentences).','The author''s central claim, while provocative, lacks empirical grounding. Key evidence is either anecdotal or drawn from limited samples. Moreover, the methodology obscures rather than clarifies the relationship. Consequently, the conclusions should be treated with considerable caution.','Use evaluative academic language.','provocative, empirical, obscure.'],
  ['policy_recommendation','Write 4 policy recommendations.','It is imperative that policymakers adopt a long-term perspective. We recommend that funding be ring-fenced for preventive measures. Moreover, it is essential that stakeholders be consulted throughout. Finally, regular independent evaluations should be mandated.','Use formal recommendations.','imperative, ring-fence, mandate.'],
  ['hedged_claim','Write 4 carefully hedged claims about research.','The evidence would suggest a correlation, though causation remains unproven. These results could, in principle, be explained by multiple factors. It seems plausible that cultural variables play a role. Further investigation is, arguably, warranted.','Use advanced hedging.','would suggest, in principle, plausible, arguably.'],
  ['review','Write a 4-sentence academic review.','This volume offers a comprehensive treatment of a neglected subject. The author marshals an impressive array of sources to support her thesis. Nevertheless, certain chapters would benefit from sharper argumentation. On balance, the book is a welcome contribution to the field.','Use balanced reviewing language.','marshal, benefit from, on balance.'],
  ['subjunctive_advanced','Write 4 sentences with advanced subjunctive.','It is essential that the protocol be followed without exception. We propose that the deadline be extended by two weeks. Be that as it may, the decision has been made. Suffice it to say, the outcome was unexpected.','Use subjunctive structures.','be that as it may, suffice it to say.'],
  ['cleft_elegant','Write 4 elegant cleft sentences.','What lies at the heart of the issue is a fundamental disagreement. It was not until the final hour that consensus was reached. The very foundation of the argument is empirical. All that is required is political will.','Use sophisticated cleft.','lies at heart, not until, very foundation.'],
  ['register_high','Write 4 sentences in highly formal register.','We are pleased to acknowledge receipt of your esteemed correspondence. Kindly accept our sincere apologies for the delay in responding. Should further clarification be required, we remain at your disposal. We look forward to our continued collaboration.','Use elevated formal style.','esteemed, sincere, at your disposal.'],
];
c1d3_mc.forEach(a=>rows.push(MC('C1',3,...a)));
c1d3_es.forEach(a=>rows.push(ES('C1',3,...a)));
};
